<a href="https://colab.research.google.com/github/harshavardhan1905/data-mining-lab-6th-sem/blob/main/week-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


In [6]:

a=np.array([[1,2,3],
            [2,3,4],
            [3,4,5]])
b=a.shape
print("shape:",a.shape)
c=a.ndim
print("dimensions:",a.ndim)
print(a)


shape: (3, 3)
dimensions: 2
[[1 2 3]
 [2 3 4]
 [3 4 5]]
